sudo: required
services:
  - docker

before_install:
  - docker build -t skilled27/workflow_with_docker -f Dockerfile.dev .

script:
  - docker run -e CI=true skilled27/workflow_with_docker npm run test